# NumPy

- NumPy (short for **Num**erical **Py**thon) is an open source Python library for doing scientific computing with Python.
- NumPy is the foundation of the python scientific stack.

## Installing numpy with pip

Use the **`!pip install numpy`** to install numpy library.

In [1]:
# Install using pip 
!pip install numpy

## Importing libraries

In [2]:
import numpy as np
import random

import warnings
warnings.filterwarnings('ignore')

print(np.__version__)

1.26.1


## List v Numpy Array

In [8]:
# Creating a list
lst = [i*random.randint(0,9) for i in range(100000)]

In [9]:
%%time
lst.sort()

CPU times: total: 31.2 ms
Wall time: 22.7 ms


In [10]:
# Converting the list into a numpy array
np_array = np.array(lst)

In [12]:
%%time
np_array.sort()

CPU times: total: 15.6 ms
Wall time: 6.86 ms


## Array creation

In [13]:
# Converting Python sequences to NumPy Arrays
a = [1, 2, 3]
print(type(a))

np_a = np.array(a)
print(type(np_a))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# 1d-array
my_list = [10.1, 2, 1]

array1d = np.array(my_list)
print(array1d)

[10.1  2.   1. ]


In [16]:
my_sublist = [
    [1.5, 2.5, 3.5, 4],
    [4.5, 5.5, 6.5, 1],
    [7.5, 8.5, 9.5, 6]
] # list of three by four list

array2d = np.array(my_sublist)
print(array2d)

[[1.5 2.5 3.5 4. ]
 [4.5 5.5 6.5 1. ]
 [7.5 8.5 9.5 6. ]]


In [17]:
array3d = np.array([
    [['R', 'G', 'B'], ['R', 'G', 'B']], 
    [['R', 'G', 'B'], ['R', 'G', 'B']]
])
print(array3d)

[[['R' 'G' 'B']
  ['R' 'G' 'B']]

 [['R' 'G' 'B']
  ['R' 'G' 'B']]]


### Some Default Attributes

In [20]:
# shape: specifies the number of elements for each dimension of the array.
print(array1d.shape, ',', array2d.shape, ',', array3d.shape)

(3,) , (3, 4) , (2, 2, 3)


In [21]:
# size: total number elements in the array
print(array1d.size, ',', array2d.size, ',', array3d.size)

3 , 12 , 12


In [23]:
# ndim: Determines the dimension an array
print(array1d.ndim, ',', array2d.ndim, ',', array3d.ndim)

1 , 2 , 3


In [24]:
# nbytes: Number of bytes used to store the data
print(array1d.nbytes, ',', array2d.nbytes, ',', array3d.nbytes)

24 , 96 , 48


In [25]:
# dtype: Determines the datatype of elements stored in array
print(array1d.dtype, ',', array2d.dtype, ',', array3d.dtype)

float64 , float64 , <U1



### Reshape an array

The **`reshape()`** method modifies existing shape but original array remains unchanged.

In [27]:
# Reshape the array
print(np_a)

# This will reshape into 3 rows and 1 column
np_a.reshape(3,1)

[1 2 3]


array([[1],
       [2],
       [3]])

In [33]:
# Reshape arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4))
print('---')
print(arr.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]



### Resize an array

The **`resize()`** method modifies existing shape and array itself.

In [37]:
# Resize arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.resize(2, 4)
print(arr)

print('---')

arr.resize(4, 2)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Some Built-in Methods for creating arrays

### arange()
Returns an array with evenly spaced elements as per the interval.

In [40]:
# arange() function
print(np.arange(10, 20))
print(np.arange(10, 30, 3))
print(np.arange(4).reshape(2,2))

[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19 22 25 28]
[[0 1]
 [2 3]]


### linspace()

Returns an array of evenly spaced values within the specified interval.

In [41]:
# linspace()
print(np.linspace(0, 10, 3))
print(np.linspace(1, 2, 6))

[ 0.  5. 10.]
[1.  1.2 1.4 1.6 1.8 2. ]


### random.randn()

Creates an array of specified shape and fills it with random values as per standard normal distribution.

In [45]:
# Standard Normal Distribution Random Number Generator
normal = np.random.randn(10000)
print(normal)

print('mean: ', np.mean(normal))
print('std. dev.:', np.std(normal))

[ 1.04595355 -2.52040477  0.74086621 ...  0.05399727  0.14676568
  0.22238181]
mean:  0.004303156919260284
std. dev.: 0.9958596324259342


### random.randint()

Creates an array of random integers in a specified intervals in a given shape. 

In [47]:
# Create a 3 x 3 array of random integers in the interval [0, 10)
print(np.random.randint(0, 10, (3, 3)))

[[3 9 8]
 [0 1 0]
 [5 9 2]]


In [48]:
# create another matrix
print(np.random.randint(0, 11, (3, 3)))

[[ 1 10  1]
 [ 9  4  7]
 [ 0  0  1]]


We got a different matrix when we generated another random matrix: We can get the same matrix again by fixing the seed.

In [69]:
# fixing the random seed
np.random.seed(0)
print(np.random.randint(0, 11, (3, 3)))

[[5 0 3]
 [3 7 9]
 [3 5 2]]


In [70]:
# fixing the random seed
np.random.seed(0)
print(np.random.randint(0, 11, (3, 3)))

[[5 0 3]
 [3 7 9]
 [3 5 2]]


### zeros() and ones()

- **zeros():** Creates an array of a given shape filled with zeroes.
- **ones():** Creates an array of a given shape filled with ones.

In [56]:
# Create a 2 X 10 integer array filled with zeros
print(np.zeros((2, 10), dtype = int))
print('----')
print(np.zeros((4, 5), dtype = int))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [57]:
# Create a 2 X 10 integer array filled with zeros
print(np.ones((2, 10), dtype = int))
print('----')
print(np.ones((4, 5), dtype = int))

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
----
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### identity()

Creates an identitity matrix of a given shape.

In [60]:
# Create a 5 x 5 identity matrix
print(np.identity(5, dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### full()

Creates a matrix by filling with any specific number of specific dimension.

In [61]:
# Create a 3 x 5 array filled with 2.14
print(np.full((3, 5), 2.14))

[[2.14 2.14 2.14 2.14 2.14]
 [2.14 2.14 2.14 2.14 2.14]
 [2.14 2.14 2.14 2.14 2.14]]


In [62]:
# Create a 2 x 4 array filled with 7
print(np.full((2, 4), 7))

[[7 7 7 7]
 [7 7 7 7]]


### eye()

Returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k.

In [63]:
# Create a 2 x 2 matrix with k = 0 (default)
print(np.eye(2, dtype = int))

[[1 0]
 [0 1]]


In [65]:
# Create a 5 x 6 matrix with k = 2, which means 1s in the 2nd diagonal from the middle one
print(np.eye(5, 6, k = 2))

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


## Array Indexing and Concatenation

In [49]:
# Create a random matrix
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[9 4 2]
 [1 1 0]
 [2 2 7]]


In [53]:
# Printing elements based on indexes
print(matrix[1][1], matrix[2][2], matrix[0][1])

1 7 4


In [78]:
# Creating 2 matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [73]:
# Concatenate along the row
matrix_row = np.concatenate([matrix1, matrix2], axis = 0)
print(matrix_row)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [74]:
# Concatenate along the column
matrix_col = np.concatenate([matrix1, matrix2], axis = 1)
print(matrix_col)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Conditional Selection

In [85]:
# Create a random matrix
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[8 1 5]
 [9 8 9]
 [4 3 0]]


In [87]:
# Returns a boolean matrix of true and false
print(matrix > 4) 

[[ True False  True]
 [ True  True  True]
 [False False False]]


In [88]:
# Creating a bool matrix on a condition
bool_matrix = matrix > 4
print(bool_matrix)

[[ True False  True]
 [ True  True  True]
 [False False False]]


In [89]:
# Showcase the elements
matrix[bool_matrix]

array([8, 5, 9, 8, 9])

In [90]:
# Values can be updated as well
matrix[matrix > 4] = 50
print(matrix)

[[50  1 50]
 [50 50 50]
 [ 4  3  0]]


## Array Broadcasting

In [79]:
# Create a random matrix
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[4 7 6]
 [8 8 1]
 [6 7 7]]


In [80]:
# Multiplying by 3
matrix_2 = matrix * 3
print(matrix_2)

[[12 21 18]
 [24 24  3]
 [18 21 21]]


In [82]:
# Adding the two matrices
print(matrix + matrix_2)

[[16 28 24]
 [32 32  4]
 [24 28 28]]


### Difference between list and numpy array

In [83]:
# Create a sample list
sample_list = [1, 2, 3, 4, 5, 6]
print(sample_list * 2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [84]:
# Create a sample numpy array
np_array = np.array(sample_list)
print(np_array * 2)

[ 2  4  6  8 10 12]


We can see that in case of list the elements are duplicated and appended to the list, whereas in case of numpy array we got an array where all elements are multiplied by 2. 