# SciPy in Python

SciPy is a open source scientific library for python. The SciPy library depends on NumPy, which provides convenient and fast N-dimensional array manipulation.

### Setting up and importing SciPy

You can install scipy from pip with the help of **`!pip install scipy`**.

In [1]:
# Installing scipy
!pip install scipy

In [4]:
# import the scipy library
import scipy

import warnings
warnings.filterwarnings('ignore')

# check the version of scipy
print(scipy.__version__)

1.13.0


### Compute the nth derivate of a function

In [8]:
# import the derivative from scipy
from scipy.misc import derivative

# define the function
def func(x):
    return x**3 + 3*x**2 + 2*x + 1

# Calculate the first derivative
print('First Derivative at x = 2:', derivative(func = func, x0 = 2))

# Calculate the second derivative
print('Second Derivative at x = 2:', derivative(func = func, x0 = 2, n = 2))

First Derivative at x = 2: 27.0
Second Derivative at x = 2: 18.0


### Permutation and Combinations

In [9]:
# Combinations
from scipy.special import comb, perm

# Total number of combinations from 4 different values taken 2 at a time: 4C2
print(comb(4, 2))

# Total number of permutations: 4P2
print(perm(4, 2))

6.0
12.0


### Linear Algebra

In [10]:
# import linear algebra module and numpy
from scipy import linalg
import numpy as np

# square matrix
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[3 6 6]
 [7 2 7]
 [1 1 5]]


In [13]:
# pass values to det() function
print('Determinant:', linalg.det(matrix))
print('Inverse:\n', linalg.inv(matrix))

Determinant: -129.0
Inverse:
 [[-0.02325581  0.18604651 -0.23255814]
 [ 0.21705426 -0.06976744 -0.1627907 ]
 [-0.03875969 -0.02325581  0.27906977]]
